const shonen=[
    {
        title:"Dragon Ball Ultimate nº 1",
        numVolume: 1,
        collection:"Dragon Ball",
        description:"Son Goku es un chico muy especial que, tras la muerte de su abuelo, vive solo en el bosque. Posee una fuerza prodigiosa y parece bastante satisfecho con su vida al aire libre hasta que conoce a Bulma, una niña pija que está buscando las Bolas de Dragón, siete esferas mágicas que, una vez reunidas, pueden conceder cualquier deseo.    Casualmente, Goku posee una de ellas, la de cuatro estrellas, por lo que a Bulma le cuesta un poco convencerle de que se una a ella en su búsqueda... ¡Así empieza el manga más popular de todos los tiempos!",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/515NTnQhd2L._SX340_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 2",
        numVolume: 2,
        collection:"Dragon Ball",
        description:"Son Goku, Bulma y Oolong continúan con la búsqueda de las Bolas de Dragón. Cuando sólo les falta una bola, llegan a un extraño pueblo atemorizado por una singular banda de conejos. Pero esto es sólo el principio de la aventura: nuestros héroes caerán en manos de un siniestro villanoque desea hacerse con las Bolas de Dragón para dominar el mundo.¿Qué ocurrirá cuando robe las Bolas? ¿Qué es lo que le pasa a Son Goku las noches de luna llena? Entra y descúbrelo…",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/510+lTmN75L._SX337_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 3",
        numVolume: 3,
        collection:"Dragon Ball",
        description:"Un anciano, una pequeña y confortable casa junto a la playa, vídeos dechicas practicando el aeróbic y un caparazón de tortuga. Pero, ¿y la emoción y la aventura? El futuro campeón del Torneo de Artes Marciales tendráque esperar a que el Duende Tortuga se decida a iniciar su entrenamiento. Son Goku y Krilín se pondrán a las órdenes del maestro Mutenroshi, pero…¿llegarán enteros al Tatami?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51pqs1JCTeL._SX340_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 4",
        numVolume: 4,
        collection:"Dragon Ball",
        description:"Para Son Goku, participar en el Torneo de Artes Marciales es un sueño hecho realidad. Pero sobre el tatami se encontrará  todo tipo de amenazasque deben combatirse con agilidad, destreza y fuerza. Y, además, ¿quién es el misterioso Jackie Chun? ¿Por qué parece saber tantas cosas sobre Goku y sus amigos? Cuando termine el torneo, ¿sobrevivirá nuestro héroe al Ejército de la RedR ibbon, empeñados también en encontrar las Bolas de Dragón",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51skxIksPvL._SX361_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 5",
        numVolume: 5,
        collection:"Dragon Ball",
        description:"Son Goku debe infiltrarse en la torre de acero del Ejercito de la Red Ribbon para liberar al alcalde de un pueblo, prisionero en el último piso. Pero el temible ninja Murasaki, tan patético como mortal, espera al chico para hacerlo servir como entrenamiento para sus tácticas secretas de asesino. Son Goku luchará en cada nivel de la torre contra monstruos, aberraciones y toda la fuerza de una organización paramilitar temida en toda laregión. Esto no es un Torneo de Artes Marciales; es un combate a vida o muerte...",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51pPYhw22RL._SX339_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 6",
        numVolume: 6,
        collection:"Dragon Ball",
        description:"Los diamantes son para siempre… O casi. Porque, ¿hay algo que pueda interponerse entre Bulma y un enemigo extremadamente guapo, una Bola de Dragón y el tesoro más descomunal que se ha encontrado desde lostiempos de los piratas? Sí, hay algo: una caverna bajo el mar que puede desmoronarse en cualquier momento, submarinos del Ejército de la Red Ribbon y un robot de alto poder destructivo…¿Hay algún tipo de descanso para tanta aventura? Sí, un lugar aparentemente idílico: ¡la Villa del Pingüino! Por lo tanto, invitada especial, ¡Arale!",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51nskPnTCdL._SX348_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 7",
        numVolume: 7,
        collection:"Dragon Ball",
        description:"Son Goku ha trepado a la interminable torre que lleva al templo de Karin, donde le espera el Agua Sagrada y un duro entrenamiento de tres días. Abajo, el pequeño indio Upa vela el cuerpo de su padre, en espera de un milagro. Pero los peligros no cesan de acosar a nuestro héroe: Tao Pai Pai, el asesino más mortal y despiadado del mundo, se prepara para eliminar a Goku y arrebatarle las Bolas de Dragón.¿Podrá esquivar Son Goku los ataques de Tao Pai Pai? ¿Sobrevivirá para resucitar al padre de Upa?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51GhblHw0dL._SX353_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 8",
        numVolume: 8,
        collection:"Dragon Ball",
        description:"Hay tatamis para todos los gustos, pero Son Goku se dispone a lucharen uno muy singular. La culminación de varios combates contra monstruos de todo tipo le llevará a enfrentarse con alguien muy especial, una persona que regresa desde el pasado y, quizá, desde otro mundo. Y hablando de ´mundo´, ¿sabéis quién es el pequeño gran tirano conmás aspiraciones de dominación mundial? En efecto, el inefable Pilaf. Conla ayuda de sus secuaces y de todo tipo de ingenios mecánicos, el villano vuelve a la carga más predispuesto que nunca a hacer el ridículo. ¿O no?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51iizNaJPqL._SX356_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 9",
        numVolume: 9,
        collection:"Dragon Ball",
        description:"Ha comenzado un nuevo Torneo de Artes Marciales y casi todos nuestros protagonistas vuelven a reunirse para demostrar el poder de sus técnicas y medirse con los luchadores más experimentados del mundo. Pero quizá la prueba más difícil de superar será la de enfrentarse entre ellos porque, ante todo, son amigos. ¿Impedirá eso que combatan con todas sus fuerzas? Mientras, detrás de la barrera, otro maestro de artes marciales conspira para que sus discípulos ganen el torneo, utilizando los métodos que sean necesarios.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51aFIs1tjqL._SX352_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 10",
        numVolume: 10,
        collection:"Dragon Ball",
        description:"Al terminar una nueva edición del torneo de Artes Marciales, un terrible crimen ha sido cometido a espaldas de nuestros protagonistas: Krilín, ha sido asesinado. Una figura diabólica podría estar detrás de todo, alguien cuyo poder rivaliza con el mismísimo Son Goku. Además, asistiremos al encuentro con una nueva amistad de Goku un poco ´pesada´ y no podremos evitar toparnos con Pilaf y su grupo de patéticos villanos.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51QAzdh2IgL._SX345_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 11",
        numVolume: 11,
        collection:"Dragon Ball",
        description:"El autoproclamado rey de los demonios, Piccolo Daimao, ha llegado a la Tierra dispuesto a convertirse en gobernante absoluto. Para convencer a los humanos de que deben rendirle pleitesía, con un simple gesto, destruye una ciudad entera. . . No queda más remedio que rendirse ante el inmenso poder de este ser. Su ideal de un mundo feliz es un lugar maravilloso donde reinen la maldad y el terror; serán los demonios los encargados de exterminar a los que luchen por la libertad y la justicia. ¿Recuperará Goku la suficiente energía como para volver al mundo de los vivos y enfrentarse a Piccolo?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51mpS3xtQhL._SX341_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 12",
        numVolume: 12,
        collection:"Dragon Ball",
        description:"Una resurrección es como un nuevo principio, al menos para todos losamigos de Son Goku a los que se les acaba de dar una segunda oportunidad y que estarán agradecidos a nuestro héroe el resto de su vida. Pero las aventuras no se acaban: en un inesperado salto en el tiempo,la historia de Dragon Ball continúa justo cuando se inaugura un nuevo Torneo de Artes Marciales. Pero todo ha cambiado, las vidas de los personajes han dado varios giros: unos han crecido, otros han envejecido, algunos han madurado…Lo que no ha cambiado es el espíritu del Torneo: sólo puede quedar uno.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51F8ESSTj6L._SX330_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 13",
        numVolume: 13,
        collection:"Dragon Ball",
        description:"¡El participante Ten Shin Han, vencedor de la última edición del Torneo de Artes Marciales, esta vez ha perdido antes de llegar a la final! El participante Son Goku, que ha demostrado tener una fuerza extraordinaria, se ha clasificado para la final. En el sexto combate se decidirá el segundo luchador de la final. Será otro combate fabuloso. Aunque esta vez los dos participantes son totalmente desconocidos, sabemos, sin embargo, que son grandes expertos. ¡Ma Junior contra Shen!",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/511sPdMroXL._SX335_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 14",
        numVolume: 14,
        collection:"Dragon Ball",
        description:"Cinco años después de la encarnizada lucha contra Piccolo Daimao,cuando el mundo volvía a estar en paz, descubriremos una nueva raza llegada del espacio. En los planetas cuyos habitantes tienen una importante fuerza de combate, emplean adultos. Pero en el caso de planetas como la Tierra, donde la gente tiene menos poder, envían a bebés. Su objetivo: la invasión total, sin piedad…Son Goku es uno de ellos.¿Se acordará de ello?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51ywATzPXyL._SX339_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 15",
        numVolume: 15,
        collection:"Dragon Ball",
        description:"Son Goku ha recorrido el eterno Camino de la Serpiente y, por fin, ha logrado encontrar a Kaito. Ahora comienza su severo entrenamiento enun pequeño planeta, cuya fuerza de gravedad es diez veces mayor quela de la Tierra. Son Gohan también se entrena, pero bajo la tutela del exigente y duro Piccolo Junior.¿Podrán padre e hijo hacer frente a la inminente llegada de la amenaza más grande del universo: los Saiyanos?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51Ohm67I6bL._SX338_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 16",
        numVolume: 16,
        collection:"Dragon Ball",
        description:"¡Los Saiyanos han llegado a la Tierra! Para nuestros héroes, cualquier otra amenaza con la que se hayan enfrentado antes queda en ridículo ante el poder ofensivo de estas criaturas del espacio exterior. Pero también traen consigo, además de un mensaje belicoso, nuevas revelaciones sobre el pasado de Son Goku, al que incluso conocen por otro nombre. Será una ocasión perfecta para poner a prueba nuevas técnicas, buscar nuevas formas de multiplicar la fuerza. . . y aprender a sobrevivir ante la magnitud de los ataques que se avecinan.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51xBXUzny3L._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 17",
        numVolume: 17,
        collection:"Dragon Ball",
        description:"La Capital del Este ha sido totalmente destruida por los Saiyanos. Las energías de los luchadores han llegado a sus mínimos. Vegeta, un guerrero realmente malvado que ha llevado el horror hasta los confines del universo, podría ser vencido. Pero quizá no se haya extirpado del todo la raíz del mal. Kaio está muy preocupado por lo que puede avecinarse. Y tiene razones para estarlo.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51vm7TAkQYL._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 18",
        numVolume: 18,
        collection:"Dragon Ball",
        description:"Freezer, el nuevo villano venido del espacio, ha aterrizado en el planeta Namek y su intención es atormentar a sus pobladores hasta que le entreguen todas las Bolas de Dragón. Quien se opone a Freezer y a sus temibles secuaces, muere de forma espantosa.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51n6yfT8thL._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 19",
        numVolume: 19,
        collection:"Dragon Ball",
        description:"Vegeta ha arrebatado a Krilín la Bola de Dragón que le dio el Gran Anciano. . . Pensó que así completaría las siete, pero no tardó en descubrir que Gohan había encontrado la que él mismo había escondido, impidiéndole así cumplir sus deseos. . . Cambiando de escondite, Krilín, Bulma y Gohan han logrado huir de la ira de Vegeta. Para despertar la fuerza que duerme en su interior, Gohan vuela con Krilín hacia la casa del Gran Anciano. ¿Lograrán llegar?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51rAUOPx8OS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 20",
        numVolume: 20,
        collection:"Dragon Ball",
        description:"Freezer está fuera de control, más loco que nunca. Quiere información.La persona que vive dentro de una misteriosa casa es el Gran Anciano de Namek, el creador de las Bolas de Dragón.Si fuera asesinado, también desaparecerían las Bolas. Si nuestros héroes no hacen lo que quiere Freezer, verán lo terrible que puede llegar a ser uno de los guerreros más poderosos del Universo.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51FtRV5lkrS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 21",
        numVolume: 21,
        collection:"Dragon Ball",
        description:"El planeta donde nacieron Vegeta y Goku no desapareció a causa de un choque contra un meteorito inmenso. . . Freezer lo destruyó, incluso cuando los guerreros le obedecían ciegamente. Sobrevivieron muy pocos guerreros. Todos los otros fueron asesinados: el padre de Goku, el padre de Vegeta, que era el rey. . . Freezer lo hizo por temor a que, de entre alguno de aquellos guerreros que cada vez eran más fuertes, surgiera el legendario Supersaiyano. Ahora, Freezer está furioso.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51luhA4EZuS._SX341_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 22",
        numVolume: 22,
        collection:"Dragon Ball",
        description:"Freezer comprueba como, por primera vez, alguien puede frenar su poder y su instinto asesino. Son Goku, un Saiyano llegado desde el planeta Tierra con el objetivo de vencerle, podría ser el legendario Supersaiyano que, aunque de pacífico corazón, sería capaz de desencadenar una violencia sin límites. Todos nuestros héroes tienen que escapar y dejar espacio a los dos luchadores, porque la energía que se liberará no tiene precedente en el Universo. Preparaos para el gran Combate a vida o muerte.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51AKPjA+PcS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 23",
        numVolume: 23,
        collection:"Dragon Ball",
        description:"¿Está a punto de llegar el fin de la Tierra? Freezer y un aliado sorpresa, su padre, llegan a nuestro planeta. No les importa la suerte que corran los terrestres, lo que realmente quieren es eliminar a todos los Supersaiyanos sea como sea. El número uno del universo tiene que ser alguien de su familia, y nadamejor que asesinar a los competidores para adjudicarse el título. La fuerza conjunta de Freezer y su padre puede acabar con cualquier héroe que intente interponerse en su camino.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51+k9PLOcwS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 24",
        numVolume: 24,
        collection:"Dragon Ball",
        description:"Nueva etapa de la serie, nuevos adversarios listos para poner a prueba el poder de Vegeta, Krilín, Piccolo y del resto de luchadores dispuestos a defender la Tierra, aunque algunos de ellos no hayan nacido en este planeta. Esta vez, son androides cargados de poder los que amenazan con traerla destrucción al mundo. Unos seres que acumulan un nivel de energía incalculable y que pueden derrotar a los guerreros más experimentados. ¿Servirá de algo la ayuda que llega desde el futuro?",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51N+Cz+rGHS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 25",
        numVolume: 25,
        collection:"Dragon Ball",
        description:"Junto a una nave llegada del espacio, Son Gohan encuentra uncaparazón vacío de un huevo de un insecto gigante. Los habitantes de un pueblo cercano han desaparecido. Piccolo viaja hasta allí y descubre al enemigo definitivo: ¡Cell! Es entonces cuando nuestros héroes deberán luchar juntos otravez para salvar nuestro planeta. Ten Shin Han y Piccolo rastrearán la energía de Cell para evitar que consiga la perfección de su cuerpo…",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51UVAYY4JyS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 26",
        numVolume: 26,
        collection:"Dragon Ball",
        description:"La llegada de Cell ha vuelto a poner en movimiento a todos nuestros héroes: Trunks y Vegeta acaban su entrenamiento, Bulma diseña ropa especial para el combate y control remoto para desactivara los androides que quieren destruir todo lo que se les pone pordelante, Goku y Son Gohan también se entrenan para mejorar susfuerza, y Vegeta, además, se prepara para desafiar a Cell en una lucha cuerpo a cuerpo…",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51W4TQ4mSoL._SX344_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 27",
        numVolume: 27,
        collection:"Dragon Ball",
        description:"Aunque Trunks lucha con todas sus fuerzas, fracasa ante Cell, el cual quiere asegurarse su dosis de diversión, y a tal efecto organiza un gran campeonato, durante el cual se enfrentará a todos los héroes de la Tierra antes de destruirla definitivamente. . . Y mientras se acerca el día del Gran Combate, el mundo entero reúne a todos los mejores luchadores. ¡Serán necesarios todos los recursos disponibles! El plazo se termina. Se acerca la hora de la verdad. El destino de nuestro Planeta está en juego.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51FMUnBnGTS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 28",
        numVolume: 28,
        collection:"Dragon Ball",
        description:"Después de combates de todo tipo, llega la hora de Son Gohan. Goku se ha rendido para cederle esa responsabilidad. Él sabe que posee una fuerza increíble cuando se enfada de verdad, pero ¡Cell no lo hace rabiar lo suficiente! Cell tiene golpes escondidos (réplicas en miniatura, pequeñas porciones de su cuerpo que tienen la capacidad de regenerarlo totalmente, etcétera) y la lucha se volverá cada vez más sangrienta.¡Uno de nuestros héroes podría morir! Mucha atención, porque este es un auténtico final de etapa para Dragon Ball. Aunque la historia, claro, continuará…",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51GdEP2kHiS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 29",
        numVolume: 29,
        collection:"Dragon Ball",
        description:"Gracias a Son Goku y a Son Gohan, la Tierra se ha liberado delas garras diabólicas de Cell y la gente puede vivir en paz y tranquilidad.Pero cuando los humanos se acostumbraron a tanta paz, volvierona surgir hombres ignorantes y malvados. Los humanos son así. Unos cuantos años después de la lucha contra Cell, todo el mundo piensa que Satán había sido el salvador de la Tierra. Incluso, laciudad donde vivía este extraño personaje cambió de nombre ensu honor: Satán City. Es aquí donde la historia de Dragon Ball continúa de forma sorprendente…",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51iVkAlJS+S._SX344_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 30",
        numVolume: 30,
        collection:"Dragon Ball",
        description:"La lista de participantes del Gran Torneo de Artes Marciales es impresionante: Son Goku, Vegeta, Piccolo, Videl, A-18, Son Gohan,Krilín…Dividido en dos categorías, infantiles y adultos, este torneo podríaser histórico en la larga lista de concursos de luchadores porque los seres más poderosos del planeta compartirán tatami de nuevo, y quizá sea por última vez. Pero no será una lucha pacífica. Alguien querrá jugar sucio, y la vida de algunos de nuestros amigos podría peligrar.¿Quiénes son los nuevos enemigos que quieren conquistar la Tierra?.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51UStm4bweS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 31",
        numVolume: 31,
        collection:"Dragon Ball",
        description:"Muchas cosas están a punto de pasar en el Gran Torneo de Artes Marciales: Goku ha encontrado el punto débil de su enemigo y espera poder seguir luchando, Babidí se pone nervioso por alguna razón, A-18 y el misterioso enmascarado asombran a Míster Satán y a todo su público, Vegeta será víctima de un conjuro y se enfrentará a Goku en un combate a muerte… Y mientras los combates suben de intensidad, alguien está a puntode despertar a la amenaza más brutal que jamás haya visto el planeta Tierra: el temible monstruo Bu.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/513OGtCzoSS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 32",
        numVolume: 32,
        collection:"Dragon Ball",
        description:"Tras la muerte de Vegeta, Píccolo y Krilín vuelven a casa con los más pequeños. Milagrosamente, el dios Kaito Shin sobrevive al ataque, consigue rescatar a Gohan y se encargará de entrenar intensivamente al chico para que pueda superar su nivel de fuerza. ¡Mientras, el monstruoso Bu continúa arrasando ciudades sin compasión! Trunks y Gates se esfuerzan para llevar a cabo la fusión, una técnica que les permitiría luchar con más poder. Parece ser que nadie puede detener a Bu. Quizá ni su propio creador sobreviva a la crueldad de este asesino",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51tYNnRYudL._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 33",
        numVolume: 33,
        collection:"Dragon Ball",
        description:"Finalmente, el monstruo Bu se enfrentará a la fusión de los más pequeños. . . De momento, Trunks y Goten se enfrentan hasta el último momento en la sala del Espíritu y el Tiempo. Piccolo pedirá a Bu que les conceda unos minutos más, ¡¡porque los chicos necesitan descansar para estar en plena forma!! Todo vale con tal de destruir a Bu y salvar una vez más al planeta Tierra de este asesino que ha destruido ciudades enteras y que ha eliminado a miles de personas.",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51rL3SAJvgL._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 34",
        numVolume: 34,
        collection:"Dragon Ball",
        description:"Ha llovido mucho desde que la joven Bulma inicia un viaje por un mundo lleno de peligros y aventuras junto con el joven Son Goku. Su objetivo: buscar las poderosas y mágicas Bolas del Dragón. ",
        genre:"shonen",
        image:"https://m.media-amazon.com/images/I/51GvntYXW2L._SX343_BO1,204,203,200_.jpg",
    },
]