const shonen=[
    
    {
        title:"Dragon Ball Ultimate nº 1",
        author:"Akira Toriyama",
        numVolume: 1,
        collectionType:"Dragon Ball",
        description:"Son Goku es un chico muy especial que, tras la muerte de su abuelo, vive solo en el bosque. Posee una fuerza prodigiosa y parece bastante satisfecho con su vida al aire libre hasta que conoce a Bulma, una niña pija que está buscando las Bolas de Dragón, siete esferas mágicas que, una vez reunidas, pueden conceder cualquier deseo.    Casualmente, Goku posee una de ellas, la de cuatro estrellas, por lo que a Bulma le cuesta un poco convencerle de que se una a ella en su búsqueda... ¡Así empieza el manga más popular de todos los tiempos!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/515NTnQhd2L._SX340_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 2",
        author:"Akira Toriyama",
        numVolume: 2,
        collectionType:"Dragon Ball",
        description:"Son Goku, Bulma y Oolong continúan con la búsqueda de las Bolas de Dragón. Cuando sólo les falta una bola, llegan a un extraño pueblo atemorizado por una singular banda de conejos. Pero esto es sólo el principio de la aventura: nuestros héroes caerán en manos de un siniestro villanoque desea hacerse con las Bolas de Dragón para dominar el mundo.¿Qué ocurrirá cuando robe las Bolas? ¿Qué es lo que le pasa a Son Goku las noches de luna llena? Entra y descúbrelo…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/510+lTmN75L._SX337_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 3",
        author:"Akira Toriyama",
        numVolume: 3,
        collectionType:"Dragon Ball",
        description:"Un anciano, una pequeña y confortable casa junto a la playa, vídeos dechicas practicando el aeróbic y un caparazón de tortuga. Pero, ¿y la emoción y la aventura? El futuro campeón del Torneo de Artes Marciales tendráque esperar a que el Duende Tortuga se decida a iniciar su entrenamiento. Son Goku y Krilín se pondrán a las órdenes del maestro Mutenroshi, pero…¿llegarán enteros al Tatami?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51pqs1JCTeL._SX340_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 4",
        author:"Akira Toriyama",
        numVolume: 4,
        collectionType:"Dragon Ball",
        description:"Para Son Goku, participar en el Torneo de Artes Marciales es un sueño hecho realidad. Pero sobre el tatami se encontrará  todo tipo de amenazasque deben combatirse con agilidad, destreza y fuerza. Y, además, ¿quién es el misterioso Jackie Chun? ¿Por qué parece saber tantas cosas sobre Goku y sus amigos? Cuando termine el torneo, ¿sobrevivirá nuestro héroe al Ejército de la RedR ibbon, empeñados también en encontrar las Bolas de Dragón",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51skxIksPvL._SX361_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 5",
        author:"Akira Toriyama",
        numVolume: 5,
        collectionType:"Dragon Ball",
        description:"Son Goku debe infiltrarse en la torre de acero del Ejercito de la Red Ribbon para liberar al alcalde de un pueblo, prisionero en el último piso. Pero el temible ninja Murasaki, tan patético como mortal, espera al chico para hacerlo servir como entrenamiento para sus tácticas secretas de asesino. Son Goku luchará en cada nivel de la torre contra monstruos, aberraciones y toda la fuerza de una organización paramilitar temida en toda laregión. Esto no es un Torneo de Artes Marciales; es un combate a vida o muerte...",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51pPYhw22RL._SX339_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 6",
        author:"Akira Toriyama",
        numVolume: 6,
        collectionType:"Dragon Ball",
        description:"Los diamantes son para siempre… O casi. Porque, ¿hay algo que pueda interponerse entre Bulma y un enemigo extremadamente guapo, una Bola de Dragón y el tesoro más descomunal que se ha encontrado desde lostiempos de los piratas? Sí, hay algo: una caverna bajo el mar que puede desmoronarse en cualquier momento, submarinos del Ejército de la Red Ribbon y un robot de alto poder destructivo…¿Hay algún tipo de descanso para tanta aventura? Sí, un lugar aparentemente idílico: ¡la Villa del Pingüino! Por lo tanto, invitada especial, ¡Arale!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51nskPnTCdL._SX348_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 7",
        author:"Akira Toriyama",
        numVolume: 7,
        collectionType:"Dragon Ball",
        description:"Son Goku ha trepado a la interminable torre que lleva al templo de Karin, donde le espera el Agua Sagrada y un duro entrenamiento de tres días. Abajo, el pequeño indio Upa vela el cuerpo de su padre, en espera de un milagro. Pero los peligros no cesan de acosar a nuestro héroe: Tao Pai Pai, el asesino más mortal y despiadado del mundo, se prepara para eliminar a Goku y arrebatarle las Bolas de Dragón.¿Podrá esquivar Son Goku los ataques de Tao Pai Pai? ¿Sobrevivirá para resucitar al padre de Upa?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51GhblHw0dL._SX353_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 8",
        author:"Akira Toriyama",
        numVolume: 8,
        collectionType:"Dragon Ball",
        description:"Hay tatamis para todos los gustos, pero Son Goku se dispone a lucharen uno muy singular. La culminación de varios combates contra monstruos de todo tipo le llevará a enfrentarse con alguien muy especial, una persona que regresa desde el pasado y, quizá, desde otro mundo. Y hablando de ´mundo´, ¿sabéis quién es el pequeño gran tirano conmás aspiraciones de dominación mundial? En efecto, el inefable Pilaf. Conla ayuda de sus secuaces y de todo tipo de ingenios mecánicos, el villano vuelve a la carga más predispuesto que nunca a hacer el ridículo. ¿O no?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51iizNaJPqL._SX356_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 9",
        author:"Akira Toriyama",
        numVolume: 9,
        collectionType:"Dragon Ball",
        description:"Ha comenzado un nuevo Torneo de Artes Marciales y casi todos nuestros protagonistas vuelven a reunirse para demostrar el poder de sus técnicas y medirse con los luchadores más experimentados del mundo. Pero quizá la prueba más difícil de superar será la de enfrentarse entre ellos porque, ante todo, son amigos. ¿Impedirá eso que combatan con todas sus fuerzas? Mientras, detrás de la barrera, otro maestro de artes marciales conspira para que sus discípulos ganen el torneo, utilizando los métodos que sean necesarios.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51aFIs1tjqL._SX352_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 10",
        author:"Akira Toriyama",
        numVolume: 10,
        collectionType:"Dragon Ball",
        description:"Al terminar una nueva edición del torneo de Artes Marciales, un terrible crimen ha sido cometido a espaldas de nuestros protagonistas: Krilín, ha sido asesinado. Una figura diabólica podría estar detrás de todo, alguien cuyo poder rivaliza con el mismísimo Son Goku. Además, asistiremos al encuentro con una nueva amistad de Goku un poco ´pesada´ y no podremos evitar toparnos con Pilaf y su grupo de patéticos villanos.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51QAzdh2IgL._SX345_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 11",
        author:"Akira Toriyama",
        numVolume: 11,
        collectionType:"Dragon Ball",
        description:"El autoproclamado rey de los demonios, Piccolo Daimao, ha llegado a la Tierra dispuesto a convertirse en gobernante absoluto. Para convencer a los humanos de que deben rendirle pleitesía, con un simple gesto, destruye una ciudad entera. . . No queda más remedio que rendirse ante el inmenso poder de este ser. Su ideal de un mundo feliz es un lugar maravilloso donde reinen la maldad y el terror; serán los demonios los encargados de exterminar a los que luchen por la libertad y la justicia. ¿Recuperará Goku la suficiente energía como para volver al mundo de los vivos y enfrentarse a Piccolo?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51mpS3xtQhL._SX341_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 12",
        author:"Akira Toriyama",
        numVolume: 12,
        collectionType:"Dragon Ball",
        description:"Una resurrección es como un nuevo principio, al menos para todos losamigos de Son Goku a los que se les acaba de dar una segunda oportunidad y que estarán agradecidos a nuestro héroe el resto de su vida. Pero las aventuras no se acaban: en un inesperado salto en el tiempo,la historia de Dragon Ball continúa justo cuando se inaugura un nuevo Torneo de Artes Marciales. Pero todo ha cambiado, las vidas de los personajes han dado varios giros: unos han crecido, otros han envejecido, algunos han madurado…Lo que no ha cambiado es el espíritu del Torneo: sólo puede quedar uno.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51F8ESSTj6L._SX330_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 13",
        author:"Akira Toriyama",
        numVolume: 13,
        collectionType:"Dragon Ball",
        description:"¡El participante Ten Shin Han, vencedor de la última edición del Torneo de Artes Marciales, esta vez ha perdido antes de llegar a la final! El participante Son Goku, que ha demostrado tener una fuerza extraordinaria, se ha clasificado para la final. En el sexto combate se decidirá el segundo luchador de la final. Será otro combate fabuloso. Aunque esta vez los dos participantes son totalmente desconocidos, sabemos, sin embargo, que son grandes expertos. ¡Ma Junior contra Shen!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/511sPdMroXL._SX335_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 14",
        author:"Akira Toriyama",
        numVolume: 14,
        collectionType:"Dragon Ball",
        description:"Cinco años después de la encarnizada lucha contra Piccolo Daimao,cuando el mundo volvía a estar en paz, descubriremos una nueva raza llegada del espacio. En los planetas cuyos habitantes tienen una importante fuerza de combate, emplean adultos. Pero en el caso de planetas como la Tierra, donde la gente tiene menos poder, envían a bebés. Su objetivo: la invasión total, sin piedad…Son Goku es uno de ellos.¿Se acordará de ello?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51ywATzPXyL._SX339_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 15",
        author:"Akira Toriyama",
        numVolume: 15,
        collectionType:"Dragon Ball",
        description:"Son Goku ha recorrido el eterno Camino de la Serpiente y, por fin, ha logrado encontrar a Kaito. Ahora comienza su severo entrenamiento enun pequeño planeta, cuya fuerza de gravedad es diez veces mayor quela de la Tierra. Son Gohan también se entrena, pero bajo la tutela del exigente y duro Piccolo Junior.¿Podrán padre e hijo hacer frente a la inminente llegada de la amenaza más grande del universo: los Saiyanos?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51Ohm67I6bL._SX338_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 16",
        author:"Akira Toriyama",
        numVolume: 16,
        collectionType:"Dragon Ball",
        description:"¡Los Saiyanos han llegado a la Tierra! Para nuestros héroes, cualquier otra amenaza con la que se hayan enfrentado antes queda en ridículo ante el poder ofensivo de estas criaturas del espacio exterior. Pero también traen consigo, además de un mensaje belicoso, nuevas revelaciones sobre el pasado de Son Goku, al que incluso conocen por otro nombre. Será una ocasión perfecta para poner a prueba nuevas técnicas, buscar nuevas formas de multiplicar la fuerza. . . y aprender a sobrevivir ante la magnitud de los ataques que se avecinan.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51xBXUzny3L._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 17",
        author:"Akira Toriyama",
        numVolume: 17,
        collectionType:"Dragon Ball",
        description:"La Capital del Este ha sido totalmente destruida por los Saiyanos. Las energías de los luchadores han llegado a sus mínimos. Vegeta, un guerrero realmente malvado que ha llevado el horror hasta los confines del universo, podría ser vencido. Pero quizá no se haya extirpado del todo la raíz del mal. Kaio está muy preocupado por lo que puede avecinarse. Y tiene razones para estarlo.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51vm7TAkQYL._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 18",
        author:"Akira Toriyama",
        numVolume: 18,
        collectionType:"Dragon Ball",
        description:"Freezer, el nuevo villano venido del espacio, ha aterrizado en el planeta Namek y su intención es atormentar a sus pobladores hasta que le entreguen todas las Bolas de Dragón. Quien se opone a Freezer y a sus temibles secuaces, muere de forma espantosa.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51n6yfT8thL._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 19",
        author:"Akira Toriyama",
        numVolume: 19,
        collectionType:"Dragon Ball",
        description:"Vegeta ha arrebatado a Krilín la Bola de Dragón que le dio el Gran Anciano. . . Pensó que así completaría las siete, pero no tardó en descubrir que Gohan había encontrado la que él mismo había escondido, impidiéndole así cumplir sus deseos. . . Cambiando de escondite, Krilín, Bulma y Gohan han logrado huir de la ira de Vegeta. Para despertar la fuerza que duerme en su interior, Gohan vuela con Krilín hacia la casa del Gran Anciano. ¿Lograrán llegar?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51rAUOPx8OS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 20",
        author:"Akira Toriyama",
        numVolume: 20,
        collectionType:"Dragon Ball",
        description:"Freezer está fuera de control, más loco que nunca. Quiere información.La persona que vive dentro de una misteriosa casa es el Gran Anciano de Namek, el creador de las Bolas de Dragón.Si fuera asesinado, también desaparecerían las Bolas. Si nuestros héroes no hacen lo que quiere Freezer, verán lo terrible que puede llegar a ser uno de los guerreros más poderosos del Universo.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51FtRV5lkrS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 21",
        author:"Akira Toriyama",
        numVolume: 21,
        collectionType:"Dragon Ball",
        description:"El planeta donde nacieron Vegeta y Goku no desapareció a causa de un choque contra un meteorito inmenso. . . Freezer lo destruyó, incluso cuando los guerreros le obedecían ciegamente. Sobrevivieron muy pocos guerreros. Todos los otros fueron asesinados: el padre de Goku, el padre de Vegeta, que era el rey. . . Freezer lo hizo por temor a que, de entre alguno de aquellos guerreros que cada vez eran más fuertes, surgiera el legendario Supersaiyano. Ahora, Freezer está furioso.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51luhA4EZuS._SX341_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 22",
        author:"Akira Toriyama",
        numVolume: 22,
        collectionType:"Dragon Ball",
        description:"Freezer comprueba como, por primera vez, alguien puede frenar su poder y su instinto asesino. Son Goku, un Saiyano llegado desde el planeta Tierra con el objetivo de vencerle, podría ser el legendario Supersaiyano que, aunque de pacífico corazón, sería capaz de desencadenar una violencia sin límites. Todos nuestros héroes tienen que escapar y dejar espacio a los dos luchadores, porque la energía que se liberará no tiene precedente en el Universo. Preparaos para el gran Combate a vida o muerte.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51AKPjA+PcS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 23",
        author:"Akira Toriyama",
        numVolume: 23,
        collectionType:"Dragon Ball",
        description:"¿Está a punto de llegar el fin de la Tierra? Freezer y un aliado sorpresa, su padre, llegan a nuestro planeta. No les importa la suerte que corran los terrestres, lo que realmente quieren es eliminar a todos los Supersaiyanos sea como sea. El número uno del universo tiene que ser alguien de su familia, y nadamejor que asesinar a los competidores para adjudicarse el título. La fuerza conjunta de Freezer y su padre puede acabar con cualquier héroe que intente interponerse en su camino.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51+k9PLOcwS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 24",
        author:"Akira Toriyama",
        numVolume: 24,
        collectionType:"Dragon Ball",
        description:"Nueva etapa de la serie, nuevos adversarios listos para poner a prueba el poder de Vegeta, Krilín, Piccolo y del resto de luchadores dispuestos a defender la Tierra, aunque algunos de ellos no hayan nacido en este planeta. Esta vez, son androides cargados de poder los que amenazan con traerla destrucción al mundo. Unos seres que acumulan un nivel de energía incalculable y que pueden derrotar a los guerreros más experimentados. ¿Servirá de algo la ayuda que llega desde el futuro?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51N+Cz+rGHS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 25",
        author:"Akira Toriyama",
        numVolume: 25,
        collectionType:"Dragon Ball",
        description:"Junto a una nave llegada del espacio, Son Gohan encuentra uncaparazón vacío de un huevo de un insecto gigante. Los habitantes de un pueblo cercano han desaparecido. Piccolo viaja hasta allí y descubre al enemigo definitivo: ¡Cell! Es entonces cuando nuestros héroes deberán luchar juntos otravez para salvar nuestro planeta. Ten Shin Han y Piccolo rastrearán la energía de Cell para evitar que consiga la perfección de su cuerpo…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51UVAYY4JyS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 26",
        author:"Akira Toriyama",
        numVolume: 26,
        collectionType:"Dragon Ball",
        description:"La llegada de Cell ha vuelto a poner en movimiento a todos nuestros héroes: Trunks y Vegeta acaban su entrenamiento, Bulma diseña ropa especial para el combate y control remoto para desactivara los androides que quieren destruir todo lo que se les pone pordelante, Goku y Son Gohan también se entrenan para mejorar susfuerza, y Vegeta, además, se prepara para desafiar a Cell en una lucha cuerpo a cuerpo…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51W4TQ4mSoL._SX344_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 27",
        author:"Akira Toriyama",
        numVolume: 27,
        collectionType:"Dragon Ball",
        description:"Aunque Trunks lucha con todas sus fuerzas, fracasa ante Cell, el cual quiere asegurarse su dosis de diversión, y a tal efecto organiza un gran campeonato, durante el cual se enfrentará a todos los héroes de la Tierra antes de destruirla definitivamente. . . Y mientras se acerca el día del Gran Combate, el mundo entero reúne a todos los mejores luchadores. ¡Serán necesarios todos los recursos disponibles! El plazo se termina. Se acerca la hora de la verdad. El destino de nuestro Planeta está en juego.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51FMUnBnGTS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 28",
        author:"Akira Toriyama",
        numVolume: 28,
        collectionType:"Dragon Ball",
        description:"Después de combates de todo tipo, llega la hora de Son Gohan. Goku se ha rendido para cederle esa responsabilidad. Él sabe que posee una fuerza increíble cuando se enfada de verdad, pero ¡Cell no lo hace rabiar lo suficiente! Cell tiene golpes escondidos (réplicas en miniatura, pequeñas porciones de su cuerpo que tienen la capacidad de regenerarlo totalmente, etcétera) y la lucha se volverá cada vez más sangrienta.¡Uno de nuestros héroes podría morir! Mucha atención, porque este es un auténtico final de etapa para Dragon Ball. Aunque la historia, claro, continuará…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51GdEP2kHiS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 29",
        author:"Akira Toriyama",
        numVolume: 29,
        collectionType:"Dragon Ball",
        description:"Gracias a Son Goku y a Son Gohan, la Tierra se ha liberado delas garras diabólicas de Cell y la gente puede vivir en paz y tranquilidad.Pero cuando los humanos se acostumbraron a tanta paz, volvierona surgir hombres ignorantes y malvados. Los humanos son así. Unos cuantos años después de la lucha contra Cell, todo el mundo piensa que Satán había sido el salvador de la Tierra. Incluso, laciudad donde vivía este extraño personaje cambió de nombre ensu honor: Satán City. Es aquí donde la historia de Dragon Ball continúa de forma sorprendente…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51iVkAlJS+S._SX344_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 30",
        author:"Akira Toriyama",
        numVolume: 30,
        collectionType:"Dragon Ball",
        description:"La lista de participantes del Gran Torneo de Artes Marciales es impresionante: Son Goku, Vegeta, Piccolo, Videl, A-18, Son Gohan,Krilín…Dividido en dos categorías, infantiles y adultos, este torneo podríaser histórico en la larga lista de concursos de luchadores porque los seres más poderosos del planeta compartirán tatami de nuevo, y quizá sea por última vez. Pero no será una lucha pacífica. Alguien querrá jugar sucio, y la vida de algunos de nuestros amigos podría peligrar.¿Quiénes son los nuevos enemigos que quieren conquistar la Tierra?.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51UStm4bweS._SX342_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 31",
        author:"Akira Toriyama",
        numVolume: 31,
        collectionType:"Dragon Ball",
        description:"Muchas cosas están a punto de pasar en el Gran Torneo de Artes Marciales: Goku ha encontrado el punto débil de su enemigo y espera poder seguir luchando, Babidí se pone nervioso por alguna razón, A-18 y el misterioso enmascarado asombran a Míster Satán y a todo su público, Vegeta será víctima de un conjuro y se enfrentará a Goku en un combate a muerte… Y mientras los combates suben de intensidad, alguien está a puntode despertar a la amenaza más brutal que jamás haya visto el planeta Tierra: el temible monstruo Bu.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/513OGtCzoSS._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 32",
        author:"Akira Toriyama",
        numVolume: 32,
        collectionType:"Dragon Ball",
        description:"Tras la muerte de Vegeta, Píccolo y Krilín vuelven a casa con los más pequeños. Milagrosamente, el dios Kaito Shin sobrevive al ataque, consigue rescatar a Gohan y se encargará de entrenar intensivamente al chico para que pueda superar su nivel de fuerza. ¡Mientras, el monstruoso Bu continúa arrasando ciudades sin compasión! Trunks y Gates se esfuerzan para llevar a cabo la fusión, una técnica que les permitiría luchar con más poder. Parece ser que nadie puede detener a Bu. Quizá ni su propio creador sobreviva a la crueldad de este asesino",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51tYNnRYudL._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 33",
        author:"Akira Toriyama",
        numVolume: 33,
        collectionType:"Dragon Ball",
        description:"Finalmente, el monstruo Bu se enfrentará a la fusión de los más pequeños. . . De momento, Trunks y Goten se enfrentan hasta el último momento en la sala del Espíritu y el Tiempo. Piccolo pedirá a Bu que les conceda unos minutos más, ¡¡porque los chicos necesitan descansar para estar en plena forma!! Todo vale con tal de destruir a Bu y salvar una vez más al planeta Tierra de este asesino que ha destruido ciudades enteras y que ha eliminado a miles de personas.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51rL3SAJvgL._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Dragon Ball Ultimate nº 34",
        author:"Akira Toriyama",
        numVolume: 34,
        collectionType:"Dragon Ball",
        description:"Ha llovido mucho desde que la joven Bulma inicia un viaje por un mundo lleno de peligros y aventuras junto con el joven Son Goku. Su objetivo: buscar las poderosas y mágicas Bolas del Dragón. ",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51GvntYXW2L._SX343_BO1,204,203,200_.jpg",
    },
    {
        title:"Ataque a los titanes nº1",
        author:" Hajime Isayama",
        numVolume: 1,
        collectionType:"Ataque a los titanes",
        description:"La raza humana, antaño dueña del mundo, se enfrenta a la extinción a manos de los titanes, gigantescos monstruos de inteligencia limitada que cazan y devoran personas por diversión. Los supervivientes se hacinan e intentan sobrevivir en una pequeña ciudad… pero algunos ya están hartos: ¡van a atacar!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71dGLrmf8qL.jpg"
    },
    {
        title:"Ataque a los titanes nº2",
        author:" Hajime Isayama",
        numVolume: 2,
        collectionType:"Ataque a los titanes",
        description:"Tras el ataque del supertitán, que consiguió traspasar el primer muro de contención de la ciudad humana, los supervivientes están aún más desesperados. Eren y sus amigos ya se han graduado como defensores de la ciudad, pero cuando los titanes atacan de nuevo, todo su entrenamiento parece inútil ante el terror que provocan…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/P/B0C1TJFBLQ.01._SCLZZZZZZZ_SX500_.jpg"
    },
    {
        title:"Ataque a los titanes nº3",
        author:" Hajime Isayama",
        numVolume: 3,
        collectionType:"Ataque a los titanes",
        description:"Un misterioso titán aparece de la nada y ataca a sus congéneres, en apariencia protegiendo a los seres humanos. ¡¿Qué está pasando?! Nadie sabe a ciencia cierta cuál es el origen de esas misteriosas criaturas, pero… ¿cabría la posibilidad de tener a alguno del lado de la humanidad?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51fpOimYxQL.jpg"
    },
    {
        title:"Ataque a los titanes nº4",
        author:" Hajime Isayama",
        numVolume: 4,
        collectionType:"Ataque a los titanes",
        description:"Ya no es un secreto que Eren puede convertirse en titán, pero Armin convence a sus superiores de que no le maten, sino que le utilicen para volver a sellar el muro. Pero el control de Eren sobre su álter ego no es completo y tiende a descontrolarse…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81j2BlUpRSL.jpg"
    },
    {
        title:"Ataque a los titanes nº5",
        author:" Hajime Isayama",
        numVolume: 5,
        collectionType:"Ataque a los titanes",
        description:"EL FUTURO DE EREN AHORA ESTÁ EN MANOS DEL CUERPO DE EXPLORACIÓN. Tras desvelarse que Eren puede convertirse en titán, un consejo decide qué hacer con él, si ejecutarlo para salvar sus almas y a los habitantes de la ciudad, o destinarlo a algún cuerpo del ejército para que ayude a la humanidad.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71WNwe210TL.jpg"
    },
    {
        title:"Ataque a los titanes nº6",
        author:" Hajime Isayama",
        numVolume: 6,
        collectionType:"Ataque a los titanes",
        description:"UN SHONEN DIFERENTE QUE ESTÁ ARRASANDO EN TODO EL MUNDO! Ahora que la condición de Eren como titán es conocida por todos, el cuerpo de exploración está dispuesto a aprovechar sus capacidades especiales en su lucha contra los terribles titanes. Pero durante una misión aparece un titán hembra que da muestras de una gran inteligencia… ¡muy similar a la de Eren!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/P/B0C1TH4BZN.01._SCLZZZZZZZ_SX500_.jpg"
    },
    {
        title:"Ataque a los titanes nº7",
        author:" Hajime Isayama",
        numVolume: 7,
        collectionType:"Ataque a los titanes",
        description:"NUEVO VOLUMEN DE SHINGEKI NO KYOJIN, EL MANGA REVELACIÓN DEL AÑO. Se desvela el objetivo real de Edwin Smith , que no es otro que atrapar a la titán hembra pero no solo para investigarla… sino porque sospecha que es uno de los gigantes dotados de inteligencia. Y como tal, es muchísimo más peligroso para la raza humana...",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71uO8ggGxLL.jpg"
    },
    {
        title:"Ataque a los titanes nº8",
        author:" Hajime Isayama",
        numVolume: 8,
        collectionType:"Ataque a los titanes",
        description:"UN NUEVO VOLUMEN DEL MANGA QUE ARRASA EN TODO EL MUNDO. Hay algo aún más aterrador que un supertitán, y es un titán con inteligencia, un humano que, como Eren, se puede transformar en gigante… pero cuyo objetivo es destruir a la raza humana. Y por lo tanto, ¡hay que capturarlo!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71DrTou4xWL.jpg"
    },
    {
        title:"Ataque a los titanes nº9",
        author:" Hajime Isayama",
        numVolume: 9,
        collectionType:"Ataque a los titanes",
        description:"No ha sido fácil, pero Eren y el resto de su grupo consiguen capturar al titán hembra con vida. Pero lo que no esperaban es la sorpresa que se oculta en el interior de los muros que les rodean ni la inesperada noticia de que el muro Rose ha caído!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71isgl8UrLL.jpg"
    },
    {
        title:"Ataque a los titanes nº10",
        author:" Hajime Isayama",
        numVolume: 10,
        collectionType:"Ataque a los titanes",
        description:"¡EL MANGA QUE HA PULVERI ZADO TODOS LOS RÉCORDS DE VENTAS MUNDIALES! Los titanes se han infiltrado dentro del muro, lo que significa que, de algún modo, han conseguido abrir una brecha. Todos los esfuerzos se centran en encontrar esa grieta, pero… ¿y si están todos equivocados?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71w+u1wXuUL.jpg"
    },
    {
        title:"Ataque a los titanes nº11",
        author:" Hajime Isayama",
        numVolume: 11,
        collectionType:"Ataque a los titanes",
        description:"¡HAY MÁS TRAIDORES EN EL CUERPO DE EXPLORACIÓN! ¿POR QUÉ EREN SIGUE SIENDO SU OBJETIVO? El cuerpo de exploración está perplejo: tras la aparición de titanes dentro del muro, son incapaces de encontrar la brecha que, por lógica, han tenido que usar para acceder a las zonas protegidas por los humanos. Y por si fuera poco, descubren que hay traidores entre ellos…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/812JNJkaSOL.jpg"
    },
    {
        title:"Ataque a los titanes nº12",
        author:" Hajime Isayama",
        numVolume: 12,
        collectionType:"Ataque a los titanes",
        description:"POR FIN LOS TITANES TIENEN A EREN EN SU PODER... ¿QUÉ SERÁ LO QUE QUIEREN DE ÉL? Los miembros de la promoción 104 están perplejos y asustados: no solo los traidores a la raza humana formaban parte de su grupo, eran compañeros en los que confiaban",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/P/B0C1TGXTSF.01._SCLZZZZZZZ_SX500_.jpg"
    },
    {
        title:"Ataque a los titanes nº13",
        author:" Hajime Isayama",
        numVolume: 13,
        collectionType:"Ataque a los titanes",
        description:"ANTIGUAS INTRIGAS , TRAICIONES Y TERR OREN ESTE NUEVO VOLUMEN DEL MANGA DELMOMENTOEl plan de Reiner y Bertolt consistía en llevar a sus reheneshasta su pueblo natal, pero no contaban con que suscompañeros de promoción harán lo que esté en su manopor liberar a sus amigos.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/P/B0C1TGT5FJ.01._SCLZZZZZZZ_SX500_.jpg"
    },
    {
        title:"Ataque a los titanes nº14",
        author:" Hajime Isayama",
        numVolume: 14,
        collectionType:"Ataque a los titanes",
        description:"EL CUERPO DE EXPLORACIÓN DECIDE… ¡¡REBE LARSE!! El objetivo de la policía militar central, que está bajo las órdenes directas del rey, es capturar a Eren e Historia. El cuerpo de exploración, ante el desenfreno del rey, ¡decide derrocar a la monarquía!",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51OgTyu09oL.jpg"
    },
    {
        title:"Ataque a los titanes nº15",
        author:" Hajime Isayama",
        numVolume: 15,
        collectionType:"Ataque a los titanes",
        description:"¡EMOCIONANTE VOLUMEN LLENO DE INTRIGA Y REVELACIONES SOBRE EL PASADO! El secuestro de Eren e Historia es la gota que ha colmado el vaso: ni Levi ni Edwin ni sus aliados están dispuestos a seguir bailando al son del gobierno, y están más decididos que nunca a derrocar a la falsa monarquía.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51RrlTN-IGL.jpg"
    },
    {
        title:"Ataque a los titanes nº16",
        author:" Hajime Isayama",
        numVolume: 16,
        collectionType:"Ataque a los titanes",
        description:"¡LEVI Y SU GRUPO AVERIGUAN DÓNDE RETIENEN A EREN, Y LO ARRIESGARÁN TODO PARA RESCATARLE! El cuerpo de exploración, a pesar de haber sido difamado por la policía militar central, logra derribar a la monarquía con la colaboración de todos los cuerpos militares. Ya solo queda hacer que el rey abdique en favor de la reina Historia, que es miembro de la familia real auténtica, ¿pero podrán convencerla?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51ag7YX8wdL.jpg"
    },
    {
        title:"Ataque a los titanes nº17",
        author:" Hajime Isayama",
        numVolume: 17,
        collectionType:"Ataque a los titanes",
        description:"ES EL MOMENTO DE DERROCAR A LA MONARQUÍA… ¿PERO PODRÁN CORONAR A SU REINA? El cuerpo de exploración se ha convertido en el grupo de rebeldes dispuesto a derrocar al gobierno corrupto y coronar a la verdadera dinastía que debe gobernar a los humanos. Y para ello, Historia deberá arriesgarlo todo...",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/P/B0C1THKW88.01._SCLZZZZZZZ_SX500_.jpg"
    },
    {
        title:"Ataque a los titanes nº18",
        author:" Hajime Isayama",
        numVolume: 18,
        collectionType:"Ataque a los titanes",
        description:"INTENTAN RECUPERAR EL MURO MARIA, PERO LOS VIGILAN MUY DE CERCA... Tras derrocar al gobierno monárquico y expulsar a la facción del antiguo régimen, las preparaciones para la operación de recuperación del muro Maria avanzan paso a paso, gracias al mineral luminoso que han obtenido recientemente y a la capacidad de endurecimiento de Eren.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/510PFq2JFfL.jpg"
    },
    {
        title:"Ataque a los titanes nº19",
        author:" Hajime Isayama",
        numVolume: 19,
        collectionType:"Ataque a los titanes",
        description:"PARA OBTENER UNA AUTÉNTICA VICTORIA, EL CUERPO DE EXPLORACIÓN DEBE RECUPERAR EL MURO MARIA. La operación consiste en usar la capacidad de endurecimiento de Eren para tapar el agujero del muro Maria en el distrito de Shiganshina para, a continuación, ir al sótano de la casa donde nació Eren con la intención de descubrir la verdad que se oculta allí.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71b3eJC6lfL.jpg"
    },
    {
        title:"Ataque a los titanes nº20",
        author:" Hajime Isayama",
        numVolume: 20,
        collectionType:"Ataque a los titanes",
        description:"El cuerpo de exploración realiza una operación de recuperación del muro Maria para descubrir la verdad que se oculta en la casa donde nació Eren. En el camino, Reiner, Bertolt y el titán animal esperan para atacarles. ¿Lograrán Eren y los demás salir victoriosos del combate contra sus antiguos compañeros y descubrir la verdad?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/71ZtnkfJY9L.jpg"
    },
    {
        title:"Ataque a los titanes nº21",
        author:" Hajime Isayama",
        numVolume: 21,
        collectionType:"Ataque a los titanes",
        description:"¡LAS LUCHAS EN TORNO A LA MISTERIOSA ISLA LLEGAN A SU PUNTO ÁLGIDO EN ESTE TOMO FINAL! Ryô se apresura a ir con Kaito y los demás miembros de la resistencia a la zona de reclusión especial central para rescatar a Mari. Sin embargo, numerosos enemigos obstaculizan su camino. ¿Logrará Ryô rescatar a Mari sana y salva?! ¿Y descubriremos qué relación hay entre el enigma esclarecido de Área D, la cárcel de la isla solitaria, y lo que trama Rei Kazaragi?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/61RPfSEOF4L.jpg"
    },
    {
        title:"Ataque a los titanes nº22",
        author:" Hajime Isayama",
        numVolume: 22,
        collectionType:"Ataque a los titanes",
        description:"EL DIARIO DEL PADRE DE EREN LES DESVELA SECRETOS SORPRENDENTES...Tras la terrible batalla contra los titanes, en especial contra el titán animal, el cuerpo de exploración llega a la casa natal de Eren, pero el secreto que se oculta en el sótano no es en absoluto lo que se esperaban. ¿Qué camino deberán seguir ante la verdad del mundo que se les ha revelado?",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/61IAeiDUoeL.jpg"
    },
    {
        title:"Ataque a los titanes nº23",
        author:" Hajime Isayama",
        numVolume: 23,
        collectionType:"Ataque a los titanes",
        description:"EREN PENSABA QUE AL OTRO LADO DEL MAR ENCONTRARÍAN LA LIBERTAD , PERO ... Llegar hasta el mar solo es el primer paso: más allá de las olas se disputa una terrible batalla entre los eldianos y los marleyanos. Y para ellos, no hay mayor honor que demostrar su valor en combate para ser dignos de poseer los poderes de un titán…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/614AQMGYjbL.jpg"
    },
    {
        title:"Ataque a los titanes nº24",
        author:" Hajime Isayama",
        numVolume: 24,
        collectionType:"Ataque a los titanes",
        description:"HAY TODO UN MUNDO TRAS LOS MUROS DONDE VIVEN EREN Y COMPAÑÍA... Fuera de la isla Paradis, donde viven Eren y compañía, se extiende un mundo donde viven otros seres humanos.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51lkiRlYn7L.jpg"
    },
    {
        title:"Ataque a los titanes nº25",
        author:" Hajime Isayama",
        numVolume: 25,
        collectionType:"Ataque a los titanes",
        description:"Los marleyanos llevan muchos años amenazando la isla Paradis, donde viven Eren y sus amigos. En Marley hay gente luchando, día tras día, para proteger su patria y defender sus derechos humanos. Con la intención de demostrar el valor de su existencia, se preparan para declarar la guerra a la isla Paradis, pero entonces aparece alguien inesperado…",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81IKt8s4m6L.jpg"
    },
    {
        title:"Ataque a los titanes nº26",
        author:" Hajime Isayama",
        numVolume: 26,
        collectionType:"Ataque a los titanes",
        description:"Marley estaba exponiendo la amenaza que suponía la isla paradis para el mundo entero, cuando apareció eren jaeger, el traidor a la paz. Mientras eren y el titán martillo de guerra luchan intensamente, ¡se produce un choque entre las mayores fuerzas de combate de ambos países.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81v0GbZQx8L.jpg"
    },
    {
        title:"Ataque a los titanes nº27",
        author:" Hajime Isayama",
        numVolume: 27,
        collectionType:"Ataque a los titanes",
        description:"La crisis se cierne sobre los habitantes de la isla Paradis... Eren entra clandestinas en Marley y provoca muchos estragos. Su objetivo era regresar a El dia con zeke. Al acogerle, como tiene sangre real, los el dia nos obtienen la condición necesaria para la activación del estruendo que Arrolla la tierra, la fuerza con la que se opondrán al mundo entero. Pero esa será, al mismo tiempo, la señal que dé comienzo a la cuenta atrás para una guerra total.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/51aoNov1SzL.jpg"
    },
    {
        title:"Ataque a los titanes nº28",
        author:" Hajime Isayama",
        numVolume: 28,
        collectionType:"Ataque a los titanes",
        description:"¿Conseguirán encontrarse eren y zeke? Eren y compañía han acogido a zeke, que tiene sangre real, consiguiendo así la condición necesaria para la activación del estruendo que Arrolla la tierra. Pero el ejército considera que hay peligro de que zeke manipule a eren y vacila en dejar que los dos hermanos se encuentren. Entonces, detienen a los soldados voluntarios de Marley. Una parte de los soldados el dia nos y del pueblo está descontenta ante esta situación y, al final, eren decide actuar por su cuenta...",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/813L2i7Xv+L.jpg"
    },
    {
        title:"Ataque a los titanes nº29",
        author:" Hajime Isayama",
        numVolume: 29,
        collectionType:"Ataque a los titanes",
        description:"El verdadero plan de zeke sale a la luz... Con la intención de activar el estruendo que Arrolla la tierra, los juristas se han alzado contra el ejército. Asesinaron al generalísimo zacklay y detuvieron a los militares más importantes. Ahora van a encontrarse con zeke, que estaba bajo la custodia de Levi. Este ha logrado capturarle otra vez, tras un combate a muerte, pero entonces...",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81hm3y2xEhL.jpg"
    },
    {
        title:"Ataque a los titanes nº30",
        author:" Hajime Isayama",
        numVolume: 30,
        collectionType:"Ataque a los titanes",
        description:"Si eren y zeke entran en contacto, será el fin de los el dia nos... El plan que zeke le ha encomendado a eren consiste en aplicar la eutanasia a todos los el dia nos. La clave del plan está en que eren, que tiene el poder del titán fundador, y zeke, que es un titán de sangre real, entren en contacto. Pero cuando zeke logra escapar y abrir se paso a través del cerco formado por Levi y el cuerpo de exploración, aparece el ejército mar Ley a no...",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81HUy-YrZML.jpg"
    },
    {
        title:"Ataque a los titanes nº31",
        author:" Hajime Isayama",
        numVolume: 31,
        collectionType:"Ataque a los titanes",
        description:"Eren consigue el poder de ymir y una armada de ti tan es colosales se pone en marcha zeke le encomienda a eren el plan de la eutanasia. Ambos rompen el cerco y logran entrar en contacto, que es la clave del plan. Sin embargo, el auténtico plan de eren era traicionar a zeke, destruyendo el mundo por medio del estruendo que Arrolla la tierra. La lucha entre los dos hermanos por el poder de la fundadora ymir termina con la victoria de eren y, por fin, una multitud de ti tan es colosales empieza una gran marcha.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81T4m9o8TzL.jpg"
    },
    {
        title:"Ataque a los titanes nº32",
        author:" Hajime Isayama",
        numVolume: 32,
        collectionType:"Ataque a los titanes",
        description:"¿EN QUÉ SE HA CONVERTIDO EREN? ¿EN UNALVADOR O EN UN GENOCIDA?ren ha obtenido el poder del titán Fundador y, por la paz de Paradis, la isladonde nació y creció, decide erradicar a la raza humana que vive fuera de la isla. Por ello, inicia la marcha junto a una legión de titanes. Sin que se haya llegado a ninguna conclusión, el grupo de Mikasa y Armin empieza a actuar parasalvar al mundo.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81GfD7a9XQL.jpg"
    },
    {
        title:"Ataque a los titanes nº33",
        author:" Hajime Isayama",
        numVolume: 33,
        collectionType:"Ataque a los titanes",
        description:"¡PENÚLTIMO TOMO PARA LLEGAR AL DESENLACE DETAQUE A LOS TITANES!ren continúa avanzando mediante el estruendo que arrolla la tierra con lantención de deshacerse de todos los humanos del mundo, a excepción dea isla Paradis. Mikasa, Armin y su grupo quieren ir a Odiha, donde existe la posibilidad de llevar a cabo la revisión del hidroavión que les permitirá perseguir Eren por el cielo. Pero, para ello, deberán renunciar a Liberio, dondeiven las familias de Annie, Reiner y compañía.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/81SDEhXFKlS.jpg"
    },
    {
        title:"Ataque a los titanes nº34",
        author:" Hajime Isayama",
        numVolume: 34,
        collectionType:"Ataque a los titanes",
        description:"¡LLEGAMOS AL ESPERADO FINAL DE ATAQUE A LOS TITANES! El estruendo va aplastando toda la tierra, a excepción de la isla Paradis, y va arrebatando vidas, una tras otra. Armin, Mikasa y los demás han averiguado cuál es el blanco de ataque de Eren y, a pesar de que entre enemigos, aliados y antiguos compañeros, están perdiendo a muchísima gente, por fin alcanzan a Eren.",
        genre:"Shonen",
        image:"https://m.media-amazon.com/images/I/41kjI546oEL.jpg"
    },
]
const mongoose = require("mongoose");
const Manga = require("../models/Manga.model");
mongoose
  .connect("mongodb://127.0.0.1:27017/todo-manga")
  .then(() => {
    return Manga.insertMany(shonen)
  })
  .then(() => {
    console.log("Información insertada en la base de datos.");
  })
  .catch((error) => {
    console.log(error);
  });