const seinen=[
    {
        title:"Maximum Berserk 1",
        numVolume: 1,
        collection:"Berserk",
        description:"Edición de lujo de una de las más aclamadas series manga de todos los tiempos. Un viaje épico y salvaje a un reino de fantasía. Guts es un guerrero vestido de negro de los pies a la cabeza que porta una gigantesca espada más larga que su propia estatura y un robusto brazo ortopédico de hierro... Allá adonde va se forman ríos de sangre y montañas de cadáveres. Cuando estaba en un aprieto, el elfo Puck recibe la ayuda del enigmático guerrero, tras lo cual decide seguirle. Puck, impresionado con el increíble poder de Guts, no puede hacer más que temblar ante el espeluznante mundo en el que este mora. Hordas de espectros tratan de impedir que avance hacia su objetivo... ¿¡Y qué es el “estigma” que tiene en la nuca!? ¿¡Le estará empujando hacia la venganza!?",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema001y_0.jpg",
    },
    {
        title:"Maximum Berserk 2",
        numVolume: 2,
        collection:"Berserk",
        description:"Guts prosigue su viaje acompañado, muy a su pesar, por el elfo Puck. Tras llegar a una ciudad gobernada por el terror, se enfrasca en una lucha contra el conde, que se vendió sin quererlo al mal y, convertido en demonio, se dedica ahora a masacrar a sus súbditos. ¡Allí, Guts encuentra a los cinco Mano de Dios a los que lleva largo tiempo persiguiendo! Con el fin de arrojar luz sobre todos sus secretos, ¡¡la historia da un vuelco y nos lleva al mismísimo nacimiento de Guts...!!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema002y_0.jpg",
    },
    {
        title:"Maximum Berserk 3",
        numVolume: 3,
        collection:"Berserk",
        description:"Desde su mismísimo nacimiento, Guts jamás ha conocido el afecto por parte de otra persona. Sólo siente afinidad por Gambino, a pesar de sus continuos y horribles malos tratos, pues le ha criado como un hijo. Sin embargo, una fatídica noche, mientras trata de protegerse, termina matando a su padre adoptivo. Completamente solo, Guts sigue progresando como guerrero hasta que, después de una batalla, se topa con Griffith y su poderoso grupo de mercenarios, la Banda del Halcón, del cual acaba formando parte. Tras ganarse la confianza de Griffith, Guts protagoniza grandes hazañas en el seno de la banda. ¡¡La juventud del guerrero negro entra ahora en su edad de oro!!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema003y_0.jpg",
    },
    {
        title:"Maximum Berserk 4",
        numVolume: 4,
        collection:"Berserk",
        description:"La Banda del Halcón de Griffith no para de acumular méritos tras haber obtenido el reconocimiento de su tropa como parte del ejército regular de Midland, nación que aspira a poner fin de una vez por todas a una larga guerra con el reino de Tudor. En medio de la contienda, Guts salva a la enferma Kasca, pero los dos caen por un precipicio. Mientras él cuida de ella, afectada por una fuerte fiebre, esta empieza a contarle su pasado: cómo Griffith le salvó la vida, cómo ingresó en la Banda del Halcón y lo que siente por su comandante.",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema004y_0_1.jpg",
    },
    {
        title:"Maximum Berserk 5",
        numVolume: 5,
        collection:"Berserk",
        description:"Después de tres años intentando convencerle para que se quede, Guts decide abandonar la Banda del Halcón. El motivo es, en parte, recuperarse a sí mismo, ya que había acabado siendo la “sombra” de Griffith, quien cada vez estaba más cerca de la “luz”. Y además quiere demostrarle a Griffith que puede luchar y vencer por sus propios medios. Griffith se empeña en retenerle aunque sea por la fuerza, de modo que, al igual que el día en que se conocieron, le reta a un duelo, pero en esta ocasión la victoria de Guts es arrolladora y doblega a su líder de un solo golpe. Algo se rompe desde ese momento dentro de Griffith...",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema005y_0.jpg",
    },
    {
        title:"Maximum Berserk 6",
        numVolume: 6,
        collection:"Berserk",
        description:"Después de que Guts abandonara la Banda del Halcón, Griffith contrarió sobremanera al rey de Midland, que le encerró en prisión y le condenó a crueles torturas mientras el ejército de Midland atacaba violentamente a sus hombres. Un año más tarde, lo que queda del grupo sobrevive como puede en el exilio comandados por Kasca. Guts aparece justo a tiempo para salvarles del ataque de un escuadrón de asesinos. Guts y Kasca se reconcilian y juntos rescatan a Griffith de su encierro. ¡Es entonces cuando el rey de Midland envía los Caballeros del Perro Negro tras ellos!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema006y_0_1.jpg",
    },
    {
        title:"Maximum Berserk 7",
        numVolume: 7,
        collection:"Berserk",
        description:"¡Se ha manifestado una dimensión alternativa! Un espacio que da sentido a todo lo sucedido hasta ahora, pero donde al mismo tiempo ese pasado carece de importancia. El Beherit, de nuevo en las manos de Griffith, responde a la llamada de su corazón, derrama lágrimas de sangre y arrastra a la Banda del Halcón en pleno a esa otra dimensión. Se produce entonces el advenimoiento de cuatro seres grotescos, los Mano de dios, que anuncian que Griffith se incorpora a sus filas tras una ofrenda: la vida de sus compañeros de armas. ¡Empieza el desenfrenado banquete de los demonios! ",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema007y_0.jpg",
    },
    {
        title:"Maximum Berserk 8",
        numVolume: 8,
        collection:"Berserk",
        description:"Han pasado dos años desde el horrible “Eclipse” en que la Banda del Halcón fue aniquilada. Guts parte de viaje con el objetivo de vengarse de los Mano de Dios, a cuyas filas se ha sumado Griffith después de transmigrarse en la figura de Femto. El guerrero negro llega a una aldea donde salva a una niña raptada por unos asaltadores de caminos y descubre que la aldea es atacada también por unos elfos que devoran animales y personas. ¡Guts se da cuenta que son critauras demoníacas disfrazadas de elfos y se lanza a exterminarlos!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema008y_0.jpg",
    },
    {
        title:"Maximum Berserk 9",
        numVolume: 9,
        collection:"Berserk",
        description:"Derrotada por fin la apóstol Rosine en el Valle de la Niebla, Guts sigue su camino de venganza y topa con los Caballeros de la Santa Cadena de Hierro, una orden de caballería dependiente de la Santa Sede que seguía sus pasos. Magullado y exhausto por su batalla con Rosine, Guts es capturado e interrogado por la comandante de los caballeros, Farnese, devota creyente que dudará de sus principios tras torturar al guerrero negro. Encerrado en una jaula, Guts se da cuenta que el campamento es rodeado por seres demoníacos a punto de atacar...",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema009y_0.jpg",
    },
    {
        title:"Maximum Berserk 10",
        numVolume: 10,
        collection:"Berserk",
        description:"Una negra sombra se cierne sobre el mundo mientras Guts se encamina a la Torre de la Condena en busca de la desaparecida Kasca. En el camino se cruza con el Caballero de la Calavera, que le comunica que va a producirse un falso “eclipse” en tierra santa. En esos momentos, miles de refugiados se agolpan alrededor de la torre y en medio de la desesperación, se producen cazas de brujas y herejes. Kasca precisamente ha caído en las garras de los herejes, que la encumbran como una verdadera bruja.",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema010y_0.jpg",
    },
    {
        title:"Maximum Berserk 11",
        numVolume: 11,
        collection:"Berserk",
        description:"Guts se adentra en la Torre de la Condena, engullida por un fenómeno de ultratumba, en busca de Kasca y se encunetra rodeado por los Inquisidores de Mozgus mientras ella está a punto de ser quemada viva en la pira. El apóstol que ha transformado a Mozgus y sus fieles se dirige a la torre para intentar “crear un mundo perfecto”... ¡¡pero le falta un elemento para conseguirlo!!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema011y_0.jpg",
    },
    {
        title:"Maximum Berserk 12",
        numVolume: 12,
        collection:"Berserk",
        description:"El reencarnado Griffith ha revelado sus intenciones: hacerse con su propio imperio. Ha podido fernar el avance del ejército de Kushan que progresaba implacable por las tierras de Midland. A su lado, guiados por designios divinos, se reúnen fieros guerreros de toda condición, algunos parecen salidos del averno... Guts decide partir de viaje hacia Elfheim, la tierra natal de Puck para intentar curar a Kasca. La cueva de Godot ha sido destruida y el guerrero negro se jura a sí mismo que no volverá a perder a Kasca, pero...",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema012y_0.jpg",
    },
    {
        title:"Maximum Berserk 13",
        numVolume: 13,
        collection:"Berserk",
        description:"En el trayecto hacia Elfheim, Guts se encuentra con Isidro, Farnese y Serpico, y tras comprender que el solo no podrá proteger a Kasca, permite que les acompañe en su viaje. En un bosque mágico conocen a Schierke, la joven discípula de la bruja Flora. Esta les habla sobre el mundo humano y el fantasmagórico, los demonios y la vía demoníaca y les pide que ayuden a los habitantes de una aldea cercana que son atacados por trols.",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema013y_0.jpg",
    },
    {
        title:"Maximum Berserk 14",
        numVolume: 14,
        collection:"Berserk",
        description:"Guts acepta la proposición de Flora de proteger Enoch del ataque de los trols a cambio de una poción mágica que proteja al grupo ahora formado por el guerrero negro, Kasca, Schierke, Farnese, Serpico e Isidro. A medio mundo de distancia, los apóstoles de la Nueva Banda del Halcón, Zodd y Grunbeld atacan el Árbol de los Espíritus. Guts encuentra la armadura de berserker y empieza a utilizarla, aun a sabiendas que su uso puede acabar matándole por el esfuerzo.",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema014y_0.jpg",
    },
    {
        title:"Maximum Berserk 15",
        numVolume: 15,
        collection:"Berserk",
        description:"Una vez en la ciudad portuaria militar de Vritannis, Guts y los demás tienen muchas dificultades para conseguir un barco que los lleve a Elfhelm. Entre tanto, Schierke, que se ha acercado al puerto, se pone en peligro tras proteger a unos niños kushanos a los que perseguían unos comerciantes de personas (antiguos piratas). Isidro y Mule tratan de ayudar a las chicas enfrentándose a los piratas. ¿Conseguirán superar el peligro sin ningún adulto que los ayude?",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema015y_0.jpg",
    },
    {
        title:"Maximum Berserk 16",
        numVolume: 16,
        collection:"Berserk",
        description:"En un abrir y cerrar de ojos, Vritannis se torna un mar de sangre por el súbito ataque de las tropas pisaca de Kushan sobre el ejército de la Santa Sede, que se había reunido en la ciudad. En medio del caos, Guts y su grupo se apresuran para llegar al buque de guerra de Eath que los transportará a Elfhelm, pero encuentran el puerto infestado de soldados pisaca. Guts y Schierke intentan abrirse paso entre las hordas enemigas, ¡pero se topan con el general kushano Deva! ¡¡La exótica magia del lugarteniente aboca sobre Guts y los suyos una serie de ataques inimaginables!!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema016y_0.jpg",
    },
    {
        title:"Maximum Berserk 17",
        numVolume: 17,
        collection:"Berserk",
        description:"Guts y los suyos consiguen por fin levar anclas hacia Elfhelm, pero el fiero guerrero está gravemente herido como resultado de su duelo frontal contra el gran emperador Ganishka. A pesar de notar en las cercanías la presencia de Griffith, Guts decide zarpar de todos modos, por el bien de sus compañeros y el suyo propio. Durante la travesía marítima, todos los miembros del grupo siguen esforzándose por alcanzar sus objetivos mientras se toman un merecido e inusual respiro. ¡Sin embargo, de golpe y porrazo aparecen en el horizonte unos barcos piratas que pretenden abordarlos!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema017y_0.jpg",
    },
    {
        title:"Maximum Berserk 18",
        numVolume: 18,
        collection:"Berserk",
        description:"El mundo ha cambiado. Hasta el último rincón del planeta se extiende esta nueva realidad en la que campan a sus anchas monstruos y seres sobrenaturales de todo tipo que, sólo unas horas antes, pertenecían al ámbito de la imaginación humana. En el centro de este nuevo mundo se materializa la inmensa e imponente capital del Halcón: Falconia. Griffith, que ha visto cumplido su sueño, entra en la ciudad con su Nueva Banda del Halcón y se dispone a gobernar el mundo desde ella. El mundo transmutado enseña también sus colmillos a Guts y sus compañeros, que prosiguen su travesía marítima hasta la isla de Skellig, donde se encuentra Elfhelm. ¡¡Un barco fantasma como el de las leyendas lanza su feroz ataque!!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema018y_0.jpg",
    },
    {
        title:"Maximum Berserk 19",
        numVolume: 19,
        collection:"Berserk",
        description:"Nuestros protagonistas navegan desde Vritannis con Roderick en su bajel de guerra rumbo a Elfheim, la patria del elfo Puck, pero a medio camino un dios marino que habita en una isla remota se abalanza sobre el barco en el que viajan. ¡La enorme envergadura y poder del dios marino pone en graves apuros incluso a un Guts que se convierte en berserker!",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema019y_0.jpg",
    },
    {
        title:"Maximum Berserk 20",
        numVolume: 20,
        collection:"Berserk",
        description:"Tras librarse de la amenaza del dios marino, Guts y los suyos consiguen llegar a su objetivo: la isla de Skellig, también conocida como `Isla de los Elfos`. Sin embargo, allí los espera una serie de conjuros y trampas destinados a evitar visitas indeseadas. El grupo penetra en la isla esquivando nuevas dificultades. ¿¡Será ese el lugar en el que Kasca podrá vivir en paz!? ¿¡Lograrán una audiencia con el llamado “rey de la tormenta de pétalos”, del que se dice que podría ayudarle a recuperar la cordura!?",
        genre:"Seinen",
        image:"https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema020y_0.jpg",
    },



]